### ISSUE TITLE
Editing miscellaneous.csv

### ISSUE THREAD

**Issue by engstromyo** [Adiaslow/Pipetide-Library-Utility#15]
This series of errors occur when attempting to edit the misc subunit file :(
<img width="1322" alt="Screen Shot 2023-01-15 at 4 11 06 PM" src="https://user-images.githubusercontent.com/109691228/212575090-bba54fd3-9d10-4f98-8a4c-418225718ae3.png">

**Comment by engstromyo** [comment]
This might just be an Alex computer issue...

**Comment by Adiaslow** [comment]
@engstromyo Quick question just glancing at this, did you save the file as a ".csv"? If so, can you show me the file you are trying to use? Just attach it here and I'll take a look.

**Comment by Adiaslow** [comment]
@engstromyo Did you figure this out as well?

**Comment by engstromyo** [comment]
I figured everything out hahaha. Thank you

**Comment by Adiaslow** [comment]
@engstromyo Good, I'm glad it all worked out. You are very welcome.
